project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Hispanic Americans in Engineering and Computer Sciences"
  author:
    - Nicholas Rodriguez Weda (nar2189)
    - Angel M. Ortega (amo2189)
  repo-url: https://github.com/nickweda/edavproject
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    embed-resources: true


